// SPDX-FileCopyrightText: 2023 SAP SE
//
// SPDX-License-Identifier: Apache-2.0
//
// This file is part of FEDEM - https://openfedem.org
////////////////////////////////////////////////////////////////////////////////

#ifndef FM_ICON_PIXMAPS_H
#define FM_ICON_PIXMAPS_H

extern const char* control_xpm[];
extern const char* ctrl1ordTF_xpm[];
extern const char* ctrl1ordTFSymbol_xpm[];
extern const char* ctrl2ordTF_xpm[];
extern const char* ctrl2ordTFSymbol_xpm[];
extern const char* ctrlAdder_xpm[];
extern const char* ctrlAdderSymbol_xpm[];
extern const char* ctrlAmplifier_xpm[];
extern const char* ctrlAmplifierSymbol_xpm[];
extern const char* ctrlCompConjPole_xpm[];
extern const char* ctrlCompConjPoleSymbol_xpm[];
extern const char* ctrlComparator_xpm[];
extern const char* ctrlComparatorSymbol_xpm[];
extern const char* ctrlDeadZone_xpm[];
extern const char* ctrlDeadZoneSymbol_xpm[];
extern const char* ctrlElemIn_xpm[];
extern const char* ctrlElemOut_xpm[];
extern const char* ctrlHysteresis_xpm[];
extern const char* ctrlHysteresisSymbol_xpm[];
extern const char* ctrlIntegrator_xpm[];
extern const char* ctrlIntegratorSymbol_xpm[];
extern const char* ctrlLimDerivator_xpm[];
extern const char* ctrlLimDerivatorSymbol_xpm[];
extern const char* ctrlLimitation_xpm[];
extern const char* ctrlLimitationSymbol_xpm[];
extern const char* ctrlLogicalSwitch_xpm[];
extern const char* ctrlLogicalSwitchSymbol_xpm[];
extern const char* ctrlMultiplier_xpm[];
extern const char* ctrlMultiplierSymbol_xpm[];
extern const char* ctrlPIlimD_xpm[];
extern const char* ctrlPIlimDSymbol_xpm[];
extern const char* ctrlPd_xpm[];
extern const char* ctrlPdSymbol_xpm[];
extern const char* ctrlPi_xpm[];
extern const char* ctrlPiSymbol_xpm[];
extern const char* ctrlPid_xpm[];
extern const char* ctrlPidSymbol_xpm[];
extern const char* ctrlPlimD_xpm[];
extern const char* ctrlPlimDSymbol_xpm[];
extern const char* ctrlPlimI_xpm[];
extern const char* ctrlPlimISymbol_xpm[];
extern const char* ctrlPlimIlimD_xpm[];
extern const char* ctrlPlimIlimDSymbol_xpm[];
extern const char* ctrlPower_xpm[];
extern const char* ctrlPowerSymbol_xpm[];
extern const char* ctrlRealPole_xpm[];
extern const char* ctrlRealPoleSymbol_xpm[];
extern const char* ctrlSampleHold_xpm[];
extern const char* ctrlSampleHoldSymbol_xpm[];
extern const char* ctrlTimeDelay_xpm[];
extern const char* ctrlTimeDelaySymbol_xpm[];

extern const char* noElemsVisible_xpm[];
extern const char* someElemsVisible_xpm[];
extern const char* allElemsVisible_xpm[];
extern const char* referencePlane_xpm[];
extern const char* triad_xpm[];
extern const char* FELink_xpm[];
extern const char* spring_xpm[];
extern const char* damper_xpm[];
extern const char* revJoint_xpm[];
extern const char* ballJoint_xpm[];
extern const char* rigidJoint_xpm[];
extern const char* freeJoint_xpm[];
extern const char* prismJoint_xpm[];
extern const char* cylJoint_xpm[];
extern const char* camJoint_xpm[];
extern const char* gear_xpm[];
extern const char* rackPinon_xpm[];
extern const char* sticker_xpm[];
extern const char* loadSmall_xpm[];
extern const char* makeRelativeSensor_xpm[];
extern const char* makeSimpleSensor_xpm[];
extern const char* makeStrainRosette_xpm[];
extern const char* createRoad_xpm[];
extern const char* createTire_xpm[];
extern const char* generic_xpm[];
extern const char* fileref_xpm[];

extern const char* function_xpm[];
extern const char* external_xpm[];
extern const char* sensor_xpm[];
extern const char* f_of_x_xpm[];
extern const char* f_of_xt_xpm[];
extern const char* timeHistInputFile_xpm[];
extern const char* F_Tdamper_xpm[];
extern const char* F_Tspring_xpm[];
extern const char* K_Rspring_xpm[];
extern const char* K_Tspring_xpm[];
extern const char* C_Rdamper_xpm[];
extern const char* C_Tdamper_xpm[];
extern const char* T_Rspring_xpm[];
extern const char* T_Rdamper_xpm[];
extern const char* friction_xpm[];
extern const char* camJointFriction_xpm[];
extern const char* prismJointFriction_xpm[];
extern const char* revJointFriction_xpm[];
extern const char* gearFriction_xpm[];

extern const char* beam_xpm[];
extern const char* beamProp_xpm[];
extern const char* beamstring_xpm[];
extern const char* event_xpm[];
extern const char* events_xpm[];
extern const char* jacket_xpm[];
extern const char* material_xpm[];
extern const char* sea_xpm[];
extern const char* soilpile_xpm[];
extern const char* vesselMotion_xpm[];

extern const char* windAirFoil_xpm[];
extern const char* windBladeProp_xpm[];
extern const char* windGears_xpm[];
extern const char* windGenerator_xpm[];
extern const char* windNacelle_xpm[];
extern const char* windRotor_xpm[];
extern const char* windShaftBlue_xpm[];
extern const char* windShaftOrange_xpm[];
extern const char* windTower_xpm[];
extern const char* windTurbine_xpm[];

#endif
