// SPDX-FileCopyrightText: 2023 SAP SE
//
// SPDX-License-Identifier: Apache-2.0
//
// This file is part of FEDEM - https://openfedem.org
////////////////////////////////////////////////////////////////////////////////

#ifndef FM_ALL_FUNCTION_HEADERS_H
#define FM_ALL_FUNCTION_HEADERS_H

#include "vpmDB/FmfLinVelVar.H"
#include "vpmDB/FmfLinVar.H"
#include "vpmDB/FmfConstant.H"
#include "vpmDB/FmfSinusoidal.H"
#include "vpmDB/FmfComplSinus.H"
#include "vpmDB/FmfDelayedComplSinus.H"
#include "vpmDB/FmfWaveSinus.H"
#include "vpmDB/FmfStep.H"
#include "vpmDB/FmfScale.H"
#include "vpmDB/FmfSpline.H"
#include "vpmDB/FmfRamp.H"
#include "vpmDB/FmfSquarePuls.H"
#include "vpmDB/FmfDiracPuls.H"
#include "vpmDB/FmfLimRamp.H"
#include "vpmDB/FmfSmoothTraj.H"
#include "vpmDB/FmfDeviceFunction.H"
#include "vpmDB/FmfExternalFunction.H"
#include "vpmDB/FmfMathExpr.H"
#include "vpmDB/FmfUserDefined.H"

#endif
